### ISSUE TITLE
[feature request] support third-party clients

### ISSUE THREAD

**Issue by jie65535** [gc-mojoconsole/gc-mojoconsole-backend#1]
Request to open the third-party client player authorization port. When the client uses the player's UID to request authorization, send an email to the player for authorization. After the player agrees, the third-party client is allowed to use the UID to execute commands.

**Comment by mingjun97** [comment]
Now supportted in dev-1.2.0. 

But we don't send email to the target player to avoid the being overwhelmed. The request initialitor should give the passcode to the targetPlayer from other channel. And ask the targetPlayer reply in game, then the auth key will be embbed in mail and send to the requester(in-game fashion) or can be retrieved in subsequent api request(api fashion).

**Comment by jie65535** [comment]
Ahh, after waiting a few days for no reply, I wrote a [plugin](https://github.com/jie65535/gc-opencommand-plugin) myself to do this.

**Comment by mingjun97** [comment]
Yeah. I've seen your plugin. That's a good work!
