### ISSUE TITLE
最近是否有考虑适配新版割草机？

### ISSUE THREAD

**Issue by keqingyyds** [gc-mojoconsole/gc-mojoconsole-backend#10]
新版割草机改指令了，好多都用不了。

**Comment by mingjun97** [comment]
抱歉更新完了，最近有点忙。

已经适配啦～下载最新的release就好，前端也做了更新，可以直接使用用CDN版本或者下载`zh-cn-1.2.2`到本地部署。

测试没有问题的话麻烦把这个issue关掉哈。
