### ISSUE TITLE
mojo权限

### ISSUE THREAD

**Issue by qianyu1431** [gc-mojoconsole/gc-mojoconsole-backend#16]
我并不想给我的服务器成员拥有一些管理权限，但是我不清楚mojo需要什么权限，我目前的权限构成是"player.*","server.spawn"，当我输入/mojo的时候，他提示我无权限。

**Comment by mingjun97** [comment]
赋予mojo.*就可以啦。



发自我的iPhone


------------------ 原始邮件 ------------------
From: 止语 ***@***.***&gt;
发送时间: 08/29/2022, 05:12
To: gc-mojoconsole/gc-mojoconsole-backend ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
Subject: Re: [gc-mojoconsole/gc-mojoconsole-backend] mojo权限 (Issue #16)





 
我并不想给我的服务器成员拥有一些管理权限，但是我不清楚mojo需要什么权限，我目前的权限构成是"player.*","server.spawn"，当我输入/mojo的时候，他提示我无权限。

**Comment by qianyu1431** [comment]
好的谢谢
