### ISSUE TITLE
configuration problem

### ISSUE THREAD

**Issue by xiyan520** [gc-mojoconsole/gc-mojoconsole-backend#4]
If I want to modify the default configuration enabled for true Which file needs to be modified

**Comment by xiyan520** [comment]
is in the uncompiled source code

**Comment by mingjun97** [comment]
You can run grasscutter first. The config fill will be auto-generated.

**Comment by mingjun97** [comment]
[mojoconfig.json.zip](https://github.com/gc-mojoconsole/gc-mojoconsole-backend/files/8694528/mojoconfig.json.zip)

Or you can modify on top of this one. Put it in the same folder with mojoconsole.jar.

**Comment by xiyan520** [comment]
Isn't this configuration generated in mojoconsole?

**Comment by mingjun97** [comment]
The auto generated configuration file by mojoconsole at runtime is in English version. This is my modified version that replace English with Chinese. You are good to use the auto generated one as well.

**Comment by xiyan520** [comment]
Then can I modify the command

**Comment by mingjun97** [comment]
You mean modify command like changing `/mojo` to something else when chat with server? 

If so, you can clone the repo and make modifications at this [file](https://github.com/gc-mojoconsole/gc-mojoconsole-backend/blob/027b6fdf2de271aeca2022e46fd84ae8ce787cfe/gc-plugin/src/main/java/com/mojo/consoleplus/command/PluginCommand.java#L16) then recompile it. Simple replace the `label = "mojoconsole"` or the `aliases = {"mojo" }` to anything you like.

**Comment by xiyan520** [comment]
Example `label = "mo", usage = "mo"` I modified it like this, sent in the command window and did not respond

**Comment by mingjun97** [comment]
Did you recompile the plugin and put the newly generated jar file back into the plugins folder? Remember that restart of grasscutter is also required.

**Comment by xiyan520** [comment]
I stopped grasscutter first, deleted all the files in the plugins folder, and then started grasscutter again, but it doesn't work after logging in to the game

**Comment by xiyan520** [comment]
I put the newly compiled one in the plugins folder

**Comment by mingjun97** [comment]
That's kind of weird. In this case, the original command `/mojo` still works?

**Comment by xiyan520** [comment]
The original mojoconsole command can be used

**Comment by mingjun97** [comment]
Do you have discord? So that we can make quick discuss there.

**Comment by xiyan520** [comment]
yes i have discord

**Comment by mingjun97** [comment]
https://discord.gg/fpxfXKa4 We can use Chinese there.
