### ISSUE TITLE
[GCAuth] 客户端 1005 试图使用无效的一次性令牌登录

### ISSUE THREAD

**Issue by yijrqz777** [gc-mojoconsole/gc-mojoconsole-backend#8]
[GCAuth] 客户端 1005 试图使用无效的一次性令牌登录

**Comment by yijrqz777** [comment]
哦？，这个gcauth是在“插件文件夹下的”并且是当我安装上了mojoconsole后自动生成的，我检查了所有设置，只我有我这个电脑登录不上，

**Comment by yijrqz777** [comment]
当我把mojo控制台插件删除，我就有可以正常登陆了

**Comment by yijrqz777** [comment]
对了1005是我登录的用户名

**Comment by mingjun97** [comment]
听起来像是grasscutter的问题。有些情况下，插件不能够全部正常启动。

**Comment by yijrqz777** [comment]
这样子啊，有什么建议吗？，重新安装一遍grasscutter？请问一下，这个gcauth是干什么用的

**Comment by mingjun97** [comment]
有时候删除插件，运行一遍grasscutter，再重新安装插件就能解决。这个gcauth是实现密码认证登陆用的。如果自己建服务器，并且只有自己玩的话没必要装倒是。

**Comment by yijrqz777** [comment]
原来是这个样子啊，谢谢，我一会尝试一下，然后，我是在服务器端搭建的，我根本没有安装gcauth这个插件，它自动创建的gcauth这个文件夹，是我应该去安装gcauth插件吗，

**Comment by mingjun97** [comment]
这个我也不太清楚了。只是自己完的话。gcauth确实没有用。

**Comment by yijrqz777** [comment]
好的，明白了，感谢！
