### ISSUE TITLE
You do not have permission to use this command

### ISSUE THREAD

**Issue by lniuua** [gc-mojoconsole/gc-mojoconsole-backend#9]

**Comment by mingjun97** [comment]
Hi, do you have more information for this? More specificelly, you got this message when you try to retrieve link for control panel or when you execute command inside the control panel?

**Comment by lniuua** [comment]
> 您好，请问您有更多的消息吗？

Game end /mojo

**Comment by mingjun97** [comment]
请问问题解决了嘛？
